# deployment-login.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-login-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-django-login
  template:
    metadata:
      labels:
        app: my-django-login
    spec:
      containers:
      - name: my-django-login-container
        image: my-django-login-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-django-login-service
spec:
  selector:
    app: my-django-login
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
